name: OrganicPanda
author: Steve Thomson
description: The home of OrganicPanda
url: http://pnda.io
markdown: redcarpet
pygments: false
permalink: /:categories/:title/
weinre: true
weinre_url: http://localhost:8080/target/target-script-min.js#anonymous